FROM alpine
RUN apk update
# https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai#1013396
RUN apk add tzdata
RUN apk update && apk add python3 py3-pip

RUN mkdir -p tweetoscope
COPY requirements.txt ./tweetoscope
COPY tweet_collector/ ./tweetoscope/tweet_collector/
RUN cd tweetoscope; pip3 install -r requirements.txt; cd ..

CMD python3 ./tweetoscope/tweet_collector/main_tweet_collector.py ./tweetoscope/tweet_collector/collector-params