version: '3.3'

services:
  tweet_generator:
    image: gaspardv/tweetoscope_generator
    network_mode: "host"
  
  tweet_collector:
    image: gaspardv/tweetoscope_collector
    network_mode: "host"
  
  hawkes_estimator:
    image: gaspardv/tweetoscope_estimator
    network_mode: "host"
    
  predictor:
    image: gaspardv/tweetoscope_predictor
    network_mode: "host"
  
  learner:
    image: gaspardv/tweetoscope_leaner
    network_mode: "host"
  
  # consumer:
  #   depends_on:
  #     - kafka-service
  #   build:
  #     context: /home/gaspard/Documents/tweetoscope-2021-09/
  #     dockerfile: docker/Dockerfile.consumers
  