apiVersion: v1
kind: Pod
metadata:
  name: generator-pod
spec:
  containers:
  - name: generator-container
    image: gaspardv/tweetoscope_generator
    imagePullPolicy: Always
    tty: true
    command : ["/bin/sh","-c"]
    args: ["cd tweetoscope/tweet_generator/; ./tweet-generator params.config-deploy"]


apiVersion: v1
kind: Pod
metadata:
  name: collector-pod
spec:
  containers:
  - name: collector-container
    image: gaspardv/tweetoscope_collector
    imagePullPolicy: Always
    tty: true
    command : ["/bin/sh","-c"]
    args: ["python3 ./tweetoscope/tweet_collector/main_tweet_collector.py ./tweetoscope/tweet_collector/collector-params-deploy"]


apiVersion: v1
kind: Pod
metadata:
  name: estimator-pod
spec:
  containers:
  - name: estimator-container
    image: gaspardv/tweetoscope_estimator
    imagePullPolicy: Always
    tty: true
    command : ["/bin/sh","-c"]
    args: ["python3 ./tweetoscope/hawkes_estimator/main_estimator.py --broker_list kafka-service:9092"]
